# Generated by Django 4.0.3 on 2022-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=250)),
                ('search_date', models.DateTimeField()),
                ('prob', models.IntegerField()),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
