# Generated by Django 4.0.3 on 2022-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_alter_news_prob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='prob',
        ),
        migrations.AddField(
            model_name='news',
            name='fk_prob',
            field=models.DecimalField(decimal_places=2, default=32.5, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='lg_prob',
            field=models.DecimalField(decimal_places=2, default=65.3, max_digits=4),
            preserve_default=False,
        ),
    ]
